version: '3.7'

services:
  webapp:
    build: 
      context: ./application
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - PORT=1337
    restart: always
