version: '3.8'

services:
  lucee:
    platform: linux/amd64
    build:
      context: ./application
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=EV-14
      - APP_ENV=production
      - LUCEE_ADMIN_PASSWORD=admin123_asdasdfasd@123
      - LUCEE_ENABLE_WARMUP=false
      - LUCEE_SERVER_ADMIN_ENABLED=true
      - LUCEE_WEB_ADMIN_ENABLED=true
      - LUCEE_EXTENSIONS=D062D72F-F8A2-46F0-8CBC91325B2F067B;name=Oracle;version=12.2.0.1
      - FLAG=ev{5f7fba0db5ba58f5831c21a5bfaad84d}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 