version: '3.8'

services:
  app:
    build: ./application
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://db:27017/phonebook
      - JWT_SECRET=your_secure_jwt_secret_key_here
      - SESSION_SECRET=your_secure_session_secret_here
      - FLAG=ev{5f7fba0db5ba58f5831c21a5bfaad84d}
      - ADMIN_PASSWORD=S3cur3P@ssw0rd123!
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=phonebook
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 