version: '3.8'

services:
  app:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: report-generator-app
    restart: always
    ports:
      - "1337:80"
    environment:
      - APP_NAME=ReportGenerator
      - APP_ENV=production
      - APP_KEY=base64:kXTlgKRiVHzTZTRtLKcqJVdGxzrJK2cUZRm2C4eLsUU=
      - APP_DEBUG=false
      - APP_URL=http://localhost:1337
      - LOG_CHANNEL=stack
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=reportgenerator
      - DB_USERNAME=reportuser
      - DB_PASSWORD=secret_password_123
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - FLAG=ev{5f7fba0db5ba58f5831c21a5bfaad84d}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: report-generator-db
    restart: always
    environment:
      - MYSQL_DATABASE=reportgenerator
      - MYSQL_USER=reportuser
      - MYSQL_PASSWORD=secret_password_123
      - MYSQL_ROOT_PASSWORD=root_secret_password_456
    command: --default-authentication-plugin=mysql_native_password 