version: '3.8'

services:
  web:
    build: 
      context: ./application
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - FLAG=ev{5f7fba0db5ba58f5831c21a5bfaad84d}
    restart: unless-stopped 