version: '3.8'

services:
  blog:
    build: ./application
    container_name: blog-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - APP_TITLE=My Blog
      - APP_PORT=3000 